immudb-address = "127.0.0.1"
immudb-port = 3322
auth = true
tokenfile = "token-0.7.0"
mtls = false
servername = "localhost"
pkey = "./tools/mtls/4_client/private/localhost.key.pem"
certificate = "./tools/mtls/4_client/certs/localhost.cert.pem"
clientcas = "./tools/mtls/2_intermediate/certs/ca-chain.cert.pem"
audit-signature = "ignore"
